### ISSUE TITLE
App bar and Game Title on Display Pages Overlap

### ISSUE THREAD

**Issue by navingator** [Beamanator/Ulti-Mate#1]
The game title needs to be placed below the app bar.

**Comment by Beamanator** [comment]
Fixed in fragment_game_display.xml by adding this to top-level RelativeLayout:

`xmlns:app="http://schemas.android.com/apk/res-auto"`
`app:layout_behavior="@string/appbar_scrolling_view_behavior"`

Found this solution on [this SO question](http://stackoverflow.com/questions/33660591/putting-content-below-appbarlayout-in-a-coordinatorlayout).

**Comment by Beamanator** [comment]
Same solution for fragment_game_display_edit.xml

**Comment by Beamanator** [comment]
Other solution that should work: Add RelativeLayout to activity_game_display, change GameDisplayActivity to add fragments into that relative layout instead of the current CoordinatorLayout (id = game_container).
