### ISSUE TITLE
Add trigger points for time caps

### ISSUE THREAD

**Issue by navingator** [Beamanator/Ulti-Mate#57]
Currently, we have a means of setting time caps in the game setup activity. 

However, we currently don't do much with it outside of displaying the soft cap time in the game display activity. We should add trigger points to send notifications for time caps.

**Comment by Beamanator** [comment]
Related to #58 - probably can be implemented around the same time

**Comment by Beamanator** [comment]
Items to look at:
- [x] <s>Alarm Notifications and Timers seem to be off by a few seconds sometimes. - Looks like Alarms are based off the exact minute and Timers are based off seconds due to setup.</s> - Solved by using .setExact (new in API 19) on AlarmManager instead of .set
- [x] Change background color of timer based on soft / hard cap
- [x] <s>stack soft / hard cap notifications</s> [future?]
- [x] Make notifications look nicer (different icon, <s>maybe colors?</s> - moving this to design issue)
